# Vault file for sensitive data
# Encrypt this file with: ansible-vault encrypt group_vars/all/vault.yml

# PostgreSQL passwords
vault_postgres_password: "21042004!"

# MinIO passwords
vault_minio_password: "21042004!"

# Zot Registry passwords
vault_zot_password: "21042004!"

# Traefik Dashboard password
vault_traefik_dashboard_password: "21042004!"

# K3s
vault_k3s_token: "nguyentantai21042004!"
vault_k3s_db_password: "k3s_master"

# Rancher
vault_rancher_bootstrap_password: "21042004!"