---
# Ingress cho RabbitMQ Management UI
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management
  namespace: NAMESPACE_NAME
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    # Uncomment để enable HTTPS
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: rabbitmq.tantai.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
