# Storage servers configuration
# MinIO credentials
minio_root_user: "tantai"
minio_root_password: "{{ vault_minio_password | default('21042004') }}"

# Storage paths
storage_data_path: "/mnt/storage_data"
storage_stack_path: "/mnt/storage_data/storage-stack"

# Zot Registry configuration
zot_image: "ghcr.io/project-zot/zot-linux-amd64:v2.1.1"

# Zot Registry authentication
zot_auth_user: "tantai"
zot_auth_password: "{{ vault_zot_password | default('21042004') }}"
